ALTER TABLE "EmailInboxConnection"
ADD COLUMN IF NOT EXISTS "authType" TEXT NOT NULL DEFAULT 'imap_password',
ADD COLUMN IF NOT EXISTS "password" TEXT,
ADD COLUMN IF NOT EXISTS "imapHost" TEXT,
ADD COLUMN IF NOT EXISTS "imapPort" INTEGER DEFAULT 993,
ADD COLUMN IF NOT EXISTS "imapSecure" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "mailbox" TEXT DEFAULT 'INBOX';
